version: '3'

services:
  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    volumes:
      - 'rabbitmq_data:/bitnami'
    environment:
    - RABBITMQ_PASSWORD=admin
    - RABBITMQ_USERNAME=admin
volumes:
  rabbitmq_data:
    driver: local