version: '3.4' 

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Osito1104**
      MYSQL_DATABASE: distributedProcessing
      MYSQL_USER: david
      MYSQL_PASSWORD: david
      MARIADB_EXTRA_FLAGS: --max-connect-errors=100000 --max_connections=15500
    ports:
      - '3306:3306'